# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 16:52
from __future__ import unicode_literals

import backend.models_helper_functions
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='empty@empty.com', max_length=254, unique=True)),
                ('nickname', models.CharField(default='empty', max_length=50, unique=True)),
                ('password', models.CharField(default='empty', max_length=128)),
                ('web_url', models.CharField(default='empty', max_length=200, unique=True)),
                ('widget_url', models.CharField(default='empty', max_length=200, unique=True)),
                ('mobile_url', models.CharField(default='empty', max_length=200, unique=True)),
                ('communication_key', models.CharField(default='empty', max_length=32, unique=True)),
                ('vid', models.CharField(default='empty', max_length=32)),
                ('vid_createtime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BigImageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(default='empty', max_length=100)),
                ('image', models.ImageField(upload_to=backend.models_helper_functions.PathAndRename('user_image/Big/2017/08/16'))),
                ('extention', models.CharField(default='empty', max_length=10)),
                ('is_client', models.BooleanField(default=None)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(default='empty', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChattingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(default='empty', max_length=100)),
                ('content', models.CharField(default='empty', max_length=500)),
                ('is_client', models.BooleanField(default=None)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='empty@empty.com', max_length=254, unique=True)),
                ('nickname', models.CharField(default='empty', max_length=50, unique=True)),
                ('password', models.CharField(default='empty', max_length=128)),
                ('is_register', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('connection_num', models.IntegerField(default=0)),
                ('vid', models.CharField(default='empty', max_length=32)),
                ('vid_createtime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='EnterpriseDisplayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='empty', max_length=50)),
                ('comment', models.CharField(blank=True, default='', max_length=200)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='RobotInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='empty', max_length=150)),
                ('answer', models.CharField(default='empty', max_length=500)),
                ('keyword', models.CharField(default='empty', max_length=100)),
                ('weight', models.IntegerField(default=0)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serials', models.CharField(default='empty', max_length=50, unique=True)),
                ('is_used', models.BooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='SmallImageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(default='empty', max_length=100)),
                ('image', models.ImageField(upload_to=backend.models_helper_functions.PathAndRename('user_image/Small/2017/08/16'))),
                ('extention', models.CharField(default='empty', max_length=10)),
                ('is_client', models.BooleanField(default=None)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(default='empty', max_length=100)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.CustomerService')),
            ],
        ),
        migrations.AddField(
            model_name='chattinglog',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.CustomerService'),
        ),
        migrations.AddField(
            model_name='bigimagelog',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.CustomerService'),
        ),
    ]
