# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservice',
            name='is_register',
            field=models.BooleanField(default=False),
        ),
    ]
