# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigimagelog',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='chattinglog',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='smallimagelog',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
