# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170807_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='vid',
            field=models.CharField(default='empty', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='vid',
            field=models.CharField(default='empty', max_length=32, unique=True),
        ),
    ]
