# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_customerservice_is_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='vid',
            field=models.CharField(default='empty', max_length=32),
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='vid',
            field=models.CharField(default='empty', max_length=32),
        ),
    ]
