# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170816_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotGossipInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='empty', max_length=150)),
                ('answer', models.CharField(default='empty', max_length=500)),
                ('weight', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='bigimagelog',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chattinglog',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='robotinfo',
            name='weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='smallimagelog',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
