# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170803_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattinglog',
            name='service_id',
            field=models.CharField(blank=True, default='null', max_length=100),
        ),
    ]
