# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20170809_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseInfoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attri_name', models.CharField(default='empty', max_length=50)),
                ('attri_type', models.CharField(default='empty', max_length=50)),
                ('en_name', models.CharField(default='empty', max_length=50)),
            ],
        ),
    ]
