# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20170816_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotinfo',
            name='keyword',
            field=models.CharField(blank=True, default='empty', max_length=100),
        ),
    ]
