# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_enterpriseinfotype'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseDisplayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='empty', max_length=50)),
                ('comment', models.CharField(blank=True, default='', max_length=200)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Admin')),
            ],
        ),
        migrations.DeleteModel(
            name='EnterpriseInfoType',
        ),
    ]
