# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_robotinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='vid_createtime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customerservice',
            name='vid_createtime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
