# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chattinglog',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='customerservice',
            name='enterprise',
        ),
        migrations.RemoveField(
            model_name='imagelog',
            name='service_id',
        ),
        migrations.DeleteModel(
            name='SerialNumber',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='mobile_url',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='web_url',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='widget_url',
        ),
        migrations.AlterField(
            model_name='admin',
            name='vid',
            field=models.CharField(default='empty', max_length=32),
        ),
        migrations.DeleteModel(
            name='ChattingLog',
        ),
        migrations.DeleteModel(
            name='CustomerService',
        ),
        migrations.DeleteModel(
            name='ImageLog',
        ),
    ]
