# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170811_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secretkey', models.CharField(default='empty', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='admin',
            name='communication_key',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='vid',
        ),
    ]
