# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20170814_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='info',
            field=models.CharField(default='empty', max_length=50),
        ),
    ]
