# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_admin_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='emterprise',
            field=models.CharField(default='empty', max_length=128),
        ),
        migrations.AlterField(
            model_name='admin',
            name='info',
            field=models.CharField(default='empty', max_length=200),
        ),
    ]
